"""autorevision migratios

Revision ID: 549841ddc377
Revises: bec4d9725f74
Create Date: 2024-10-26 16:41:05.111985

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "549841ddc377"
down_revision: Union[str, None] = "bec4d9725f74"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permission",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "person",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("email", sa.String(length=250), nullable=False),
        sa.Column("picture", sa.String(length=250), nullable=True),
        sa.Column("test", sa.String(length=250), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workspace",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=250), nullable=False),
        sa.Column("capacity", sa.String(length=250), nullable=False),
        sa.Column("hourlyRate", sa.String(length=250), nullable=False),
        sa.Column("availableSchedules", sa.String(length=250), nullable=False),
        sa.Column("createdBy", sa.String(length=250), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reservation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reservedBy", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("startTime", sa.String(length=250), nullable=False),
        sa.Column("endTime", sa.String(length=250), nullable=False),
        sa.Column("status", sa.String(length=250), nullable=False),
        sa.Column("price", sa.String(length=250), nullable=False),
        sa.ForeignKeyConstraint(
            ["reservedBy"],
            ["person.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "role_permission",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permission.id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "schedule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("openingTime", sa.String(length=250), nullable=False),
        sa.Column("closingTime", sa.String(length=250), nullable=False),
        sa.Column("status", sa.String(length=250), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "promotion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=250), nullable=False),
        sa.Column("discount", sa.String(length=250), nullable=False),
        sa.Column("startTime", sa.String(length=250), nullable=False),
        sa.Column("endTime", sa.String(length=250), nullable=False),
        sa.Column("status", sa.String(length=250), nullable=False),
        sa.Column("reservation_id", sa.Integer(), nullable=False),
        sa.Column("createdBy", sa.String(length=250), nullable=False),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("promotion")
    op.drop_table("schedule")
    op.drop_table("role_permission")
    op.drop_table("reservation")
    op.drop_table("workspace")
    op.drop_table("person")
    op.drop_table("permission")
    # ### end Alembic commands ###
